### ISSUE TITLE
Fix navbar width & logo placement

### ISSUE THREAD

**Issue by danieltsoukup** [danieltsoukup/noise-dashboard#17]
**Describe the bug**
The nav bar is not consistent with the main https://tracket.info/ website, does not extend to the very end of the page and the logo is awkwardly placed. 

**To Reproduce**
Visit the dashboard on any location page, e.g.: https://dashboard.tracket.info/locations/756264 and compare with https://tracket.info/

**Expected behavior**
In this ticket, we are aiming to fix the following
- the grey navbar should go all the way to the page border,
- the bar should have the same width on the dashboard pages and https://tracket.info/
- the logo should be placed on the dashboard pages same as on https://tracket.info/ relative to the page border.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/179be469-62be-419b-8180-496e47bbbdd1">

**Relevant Code**
- Navbar: https://github.com/danieltsoukup/noise-dashboard/blob/de583d58d317584eeff7d33edf3f61feef318f85/app/src/app_components.py#L337 and navbar docs https://dash-bootstrap-components.opensource.faculty.ai/docs/components/navbar/
- CSS: https://github.com/danieltsoukup/noise-dashboard/blob/de583d58d317584eeff7d33edf3f61feef318f85/app/assets/styles.css
- App config: https://github.com/danieltsoukup/noise-dashboard/blob/de583d58d317584eeff7d33edf3f61feef318f85/app/src/config.ini

**Comment by harshiltomar** [comment]
@danieltsoukup Can I work on this issue ? Kindly assign it to me

**Comment by danieltsoukup** [comment]
Welcome to the project, @harshiltomar ! Thank you for offering to help, happy to assign you the issue. Let me know if you have any questions as you start exploring the code.

**Comment by harshiltomar** [comment]
Hey ! on running the docker image locally after `make prod_build` and `make prod_container`.It seems to be exisiting itself within a second.

on `docker logs noise-dashboard`, I get :
`[2024-08-10 08:25:27 +0000] [7] [INFO] Starting gunicorn 21.2.0
[2024-08-10 08:25:27 +0000] [7] [INFO] Listening at: http://0.0.0.0:8501 (7)
[2024-08-10 08:25:27 +0000] [7] [INFO] Using worker: sync
[2024-08-10 08:25:27 +0000] [8] [INFO] Booting worker with pid: 8
[2024-08-10 08:25:27 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/project/app/app.py", line 22, in <module>
    Logging.setup()`

**Comment by danieltsoukup** [comment]
Hey, it looks like the fail happened at the `Logging.setup()` call? The line will try to create a new log file and write to it so you can try to double-check that the container would have permissions to do that if you are not running with `sudo`. Are you running it on Mac/Win/Linux?

**Comment by harshiltomar** [comment]
Previsouly ran it from Macos from vs-terminal / mac terminal . Will check for the permissions

**Comment by danieltsoukup** [comment]
You can also try to create an `app/logs/main.log` file manually, see then if the container runs properly.

**Comment by danieltsoukup** [comment]
Hey, @harshiltomar did you manage to resolve the issue?

**Comment by danieltsoukup** [comment]
Navbar width has been fixed, leaving the logo placement as is for the moment and closing this item. @harshiltomar thanks for the interest, let me know if you're up to working on something else.
